services:
  # Cambia 'web-Telcomfib' por 'web-telcomfib' (minúsculas)
  web-telcomfib: 
    build:
      context: .
      dockerfile: Dockerfile
    # El nombre de la imagen DEBE ser en minúsculas
    image: telcomfib-web:latest 
    container_name: web-telcomfib
    ports:
      - "80:80"
    networks:
      - webtelcomfib
    restart: always

networks:
  webtelcomfib:
    driver: bridge